/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TraineeIndexRouteImport } from './routes/trainee/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as TraineeSubjectsIndexRouteImport } from './routes/trainee/subjects/index'
import { Route as AdminTraineesIndexRouteImport } from './routes/admin/trainees/index'
import { Route as AdminSubjectsIndexRouteImport } from './routes/admin/subjects/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeIndexRoute = TraineeIndexRouteImport.update({
  id: '/trainee/',
  path: '/trainee/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeSubjectsIndexRoute = TraineeSubjectsIndexRouteImport.update({
  id: '/trainee/subjects/',
  path: '/trainee/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTraineesIndexRoute = AdminTraineesIndexRouteImport.update({
  id: '/admin/trainees/',
  path: '/admin/trainees/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsIndexRoute = AdminSubjectsIndexRouteImport.update({
  id: '/admin/subjects/',
  path: '/admin/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/trainee': typeof TraineeIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
  '/admin/trainees': typeof AdminTraineesIndexRoute
  '/trainee/subjects': typeof TraineeSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/trainee': typeof TraineeIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
  '/admin/trainees': typeof AdminTraineesIndexRoute
  '/trainee/subjects': typeof TraineeSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/trainee/': typeof TraineeIndexRoute
  '/admin/subjects/': typeof AdminSubjectsIndexRoute
  '/admin/trainees/': typeof AdminTraineesIndexRoute
  '/trainee/subjects/': typeof TraineeSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/admin'
    | '/auth'
    | '/trainee'
    | '/admin/subjects'
    | '/admin/trainees'
    | '/trainee/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/admin'
    | '/auth'
    | '/trainee'
    | '/admin/subjects'
    | '/admin/trainees'
    | '/trainee/subjects'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/admin/'
    | '/auth/'
    | '/trainee/'
    | '/admin/subjects/'
    | '/admin/trainees/'
    | '/trainee/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  TraineeIndexRoute: typeof TraineeIndexRoute
  AdminSubjectsIndexRoute: typeof AdminSubjectsIndexRoute
  AdminTraineesIndexRoute: typeof AdminTraineesIndexRoute
  TraineeSubjectsIndexRoute: typeof TraineeSubjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/': {
      id: '/trainee/'
      path: '/trainee'
      fullPath: '/trainee'
      preLoaderRoute: typeof TraineeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/subjects/': {
      id: '/trainee/subjects/'
      path: '/trainee/subjects'
      fullPath: '/trainee/subjects'
      preLoaderRoute: typeof TraineeSubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainees/': {
      id: '/admin/trainees/'
      path: '/admin/trainees'
      fullPath: '/admin/trainees'
      preLoaderRoute: typeof AdminTraineesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects/': {
      id: '/admin/subjects/'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  TraineeIndexRoute: TraineeIndexRoute,
  AdminSubjectsIndexRoute: AdminSubjectsIndexRoute,
  AdminTraineesIndexRoute: AdminTraineesIndexRoute,
  TraineeSubjectsIndexRoute: TraineeSubjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
